### ISSUE TITLE
Jest 19 not accepting --teamcity CLI flag

### ISSUE THREAD

**Issue by bhouser** [winterbe/jest-teamcity-reporter#10]
With Jest 18.0.1, there is some console output like this:
```
Unrecognized options: teamcity
```
But then the tests are executed without any further problems.

With Jest 19.0.0, a more impressive error is produced, and the tests don't run at all:
```
/my/project/path/node_modules/jest-util/build/validateCLIOptions.js:59
    throw createCLIValidationError(unrecognizedOptions, allowedOptions);
    ^

● Unrecognized CLI Parameter:

  Unrecognized option "teamcity".

  CLI Options Documentation:
  http://facebook.github.io/jest/docs/cli.html


npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "run" "test:teamcity"
npm ERR! node v7.4.0
npm ERR! npm  v4.1.1
npm ERR! code ELIFECYCLE
npm ERR! MyProjectName@0.0.2 test:teamcity: `jest --teamcity`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the MyProjectName@0.0.2 test:teamcity script 'jest --teamcity'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ReactMain package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     jest --teamcity
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ReactMain
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ReactMain
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /my/project/path/reactmain/npm-debug.log
```

**Comment by rickhanlonii** [comment]
Jest 19 will fail on [invalid CLI arguments](https://facebook.github.io/jest/blog/2017/02/21/jest-19-immersive-watch-mode-test-platform-improvements.html#new-cli-arguments), so you'll need to use the `TEAMCITY_VERSION` [envar](https://github.com/winterbe/jest-teamcity-reporter#usage) instead:

```
TEAMCITY_VERSION="your_version" jest
```

**Comment by winterbe** [comment]
Haven't tested Jest 19 yet but I guess we should remove the `--teamcity` option entirely if it breaks the build.

**Comment by bhouser** [comment]
@rickhanlonii the envar solution worked.  Thanks!

@winterbe it might be helpful if at least the documentation didn't recommend the `--teamcity` option.

**Comment by winterbe** [comment]
@bhouser Thanks for your feedback. I've updated the README accordingly.

**Comment by mrobrian** [comment]
I just ran into this same issue because over at npmjs.com the README displayed for this package still shows to add --teamcity

**Comment by winterbe** [comment]
@mrobrian Sorry for the inconvenience. I've removed `--teamcity` flag entirely and published new version `0.5.0` to prevent future confusions.
